echo "Platforms: 1.android, 2.ios"
read platform

if [ ${platform} == "1" ]
then
echo ...aciflavor appbundle building...
flutter build appbundle -t lib/flavors/main_aci.dart --flavor aciflavor
echo ...acilimflavor appbundle building...
flutter build appbundle -t lib/flavors/main_acilim.dart --flavor acilimflavor
echo ...datatacflavor appbundle building...
flutter build appbundle -t lib/flavors/main_datatac.dart --flavor datatacflavor
echo ...datatacekidflavor appbundle building...
flutter build appbundle -t lib/flavors/main_datatacekid.dart --flavor datatacekidflavor
echo ...elseifekidflavor appbundle building...
flutter build appbundle -t lib/flavors/main_elseifekid.dart --flavor elseifekidflavor
echo ...elseifflavor appbundle building...
flutter build appbundle -t lib/flavors/main_elseif.dart --flavor elseifflavor
echo ...muradiyeflavor appbundle building...
flutter build appbundle -t lib/flavors/main_muradiye.dart --flavor muradiyeflavor
echo ...taktikbendeflavor appbundle building...
flutter build appbundle -t lib/flavors/main_taktikbende.dart --flavor taktikbendeflavor
echo ...teknokentflavor appbundle building...
flutter build appbundle -t lib/flavors/main_teknokent.dart --flavor teknokentflavor
echo ...speedsisflavor appbundle building...
flutter build appbundle -t lib/flavors/main_speedsis.dart --flavor speedsisflavor
elif [ ${platform} == "2" ]
then
echo ...aciflavor ipa building...
flutter build ipa -t lib/flavors/main_aci.dart --flavor aciflavor
echo ...acilimflavor ipa building...
flutter build ipa -t lib/flavors/main_acilim.dart --flavor acilimflavor
echo ...datatacflavor ipa building...
flutter build ipa -t lib/flavors/main_datatac.dart --flavor datatacflavor
echo ...datatacekidflavor ipa building...
flutter build ipa -t lib/flavors/main_datatacekid.dart --flavor datatacekidflavor
echo ...elseifekidflavor ipa building...
flutter build ipa -t lib/flavors/main_elseifekid.dart --flavor elseifekidflavor
echo ...elseifflavor ipa building...
flutter build ipa -t lib/flavors/main_elseif.dart --flavor elseifflavor
echo ...muradiyeflavor ipa building...
flutter build ipa -t lib/flavors/main_muradiye.dart --flavor muradiyeflavor
echo ...taktikbendeflavor ipa building...
flutter build ipa -t lib/flavors/main_taktikbende.dart --flavor taktikbendeflavor
echo ...teknokentflavor ipa building...
flutter build ipa -t lib/flavors/main_teknokent.dart --flavor teknokentflavor
echo ...speedsisflavor ipa building...
flutter build ipa -t lib/flavors/main_speedsis.dart --flavor speedsisflavor
open build/ios/ipa
fi