name: elseifekol
description: Ekol

version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

#//* MyPackages 

  mcg_database:
    path: ../../Flutter_Packages/mypackage/mcg_database
  mcg_extension:
    path: ../../Flutter_Packages/mypackage/mcg_extension
  mypackage:
    path: ../../Flutter_Packages/mypackage/newekolwidgetpackage
  widgetpackage:
    path: ../../Flutter_Packages/mypackage/widgetpackage
  myvideocall:
    path: ../../Flutter_Packages/mylibraries/myvideocallfake

#//* Deferred 

#//! Office 
  excel: 2.0.0-null-safety-3
  spreadsheet_decoder: ^2.1.1
  printing: ^5.9.3

#//! UI
  syncfusion_flutter_charts: ^20.3.58


#//! Tools
  screenshot: 1.2.3


#//* Eager

#//! Network
  firebase_messaging: ^14.2.1
  firebase_auth: ^4.2.5

#//! Office 
  pdfx: 2.3.0

#//! UI 
  animated_background: ^2.0.0
  animated_tree_view: 0.1.1
  animations: ^2.0.7
  timeline_tile: 2.0.0
  flutter_chat_bubble: ^2.0.0
  painter: ^2.0.0
  sleek_circular_slider: ^2.0.1
  syncfusion_flutter_calendar: 20.3.52
  animated_list_plus: 0.4.5
  flutter_math_fork: 0.6.3 

#//! Utils

  dart_jsonwebtoken: 2.7.1
  flutter_app_icon_badge: ^2.0.0
  in_app_purchase: 3.0.7
  geolocator: ^9.0.2
  ntp: ^2.0.0
  pointer_interceptor: 0.9.3+4
  random_color: 1.0.6-nullsafety
  receive_sharing_intent: ^1.4.5
  turkish: ^0.2.1
  google_fonts: ^4.0.3
  expressions: 0.2.4
  

#//! Tools

  record: 4.1.1
  audioplayers: 3.0.0
  qr_code_scanner: ^1.0.1   
  flutter_sms: 2.3.2
  flutter_inappwebview: ^5.5.0+2
  flutter_map: ^3.0.0
  collection: ^1.15.0-nullsafety.4


dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter

dependency_overrides:
  # 6 inci versiyon sonrasi icin dospace guncellenmeli
  xml: 5.4.0
  device_info_plus: ^6.0.0 




flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/gicons/
    - assets/rive/
    - assets/pattern/
    - assets/latex/
    - assets/files/kayitsozlesmesi.pdf
    - assets/localization/ekol/
    - assets/localization/website/
    - assets/localization/flags/
    - assets/website/
 
 
  fonts:
    - family: SFUI
      fonts:
        - asset: assets/fonts/SFUIText-Medium.ttf
        - asset: assets/fonts/SFUIText-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/SFUIText-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFUIText-BoldItalic.ttf
          style: italic
          weight: 700


