// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'smatqbank.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApi5aGPiEmN-LxIAbrfkN92Px_7Fe2GCY',
    appId: '1:309980956561:web:6c0d9cb89839f576',
    messagingSenderId: '309980956561',
    projectId: 'class-724',
    authDomain: 'class-724.firebaseapp.com',
    databaseURL: 'https://class-724.firebaseio.com',
    storageBucket: 'class-724.appspot.com',
    measurementId: 'G-4K49YWN356',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcFGJAPrD8WqeFHGHhPelv4Bhp8B6OO_E',
    appId: '1:309980956561:android:b07546526fecd15a',
    messagingSenderId: '309980956561',
    projectId: 'class-724',
    databaseURL: 'https://class-724.firebaseio.com',
    storageBucket: 'class-724.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWiKF3uK4b27542JTu8mso36Tq85TS8gI',
    appId: '1:309980956561:ios:b07546526fecd15a',
    messagingSenderId: '309980956561',
    projectId: 'class-724',
    databaseURL: 'https://class-724.firebaseio.com',
    storageBucket: 'class-724.appspot.com',
    androidClientId: '309980956561-0l04b4kvdl8daekbim48lus2449knqu5.apps.googleusercontent.com',
    iosClientId: '309980956561-v0l8hpniq6012i4oufkvr62ks0a0afko.apps.googleusercontent.com',
    iosBundleId: 'com.elseif.datatac.qbank',
  );
}
