// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'tua.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlEZ3UmeJMZ0475JJiWWoVoUUkJ0_vaj8',
    appId: '1:1028855526902:web:49abfe7ced217a7bd643d7',
    messagingSenderId: '1028855526902',
    projectId: 'tuaacademy-33045',
    authDomain: 'tuaacademy-33045.firebaseapp.com',
    databaseURL: 'https://tuaacademy-33045-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tuaacademy-33045.appspot.com',
    measurementId: 'G-6J843FNJN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5_N7wYF6apgm5yfwoVZdeaP0iR9aAXJw',
    appId: '1:1028855526902:android:6e6926a53ecfa7ded643d7',
    messagingSenderId: '1028855526902',
    projectId: 'tuaacademy-33045',
    databaseURL: 'https://tuaacademy-33045-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tuaacademy-33045.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ-v26D9kOFhkWAQc1axyHKceslXuwH_k',
    appId: '1:1028855526902:ios:21faf8fcff917506d643d7',
    messagingSenderId: '1028855526902',
    projectId: 'tuaacademy-33045',
    databaseURL: 'https://tuaacademy-33045-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tuaacademy-33045.appspot.com',
    iosClientId: '1028855526902-r9fcmu03ue9ken9nvellm44htt0krbke.apps.googleusercontent.com',
    iosBundleId: 'com.elseif.tua',
  );
}
