// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'ecolerrors.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class EcollErrorsFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeIOv7Hg3jzCbrRxQ7kJOjkpdg_ikJujY',
    appId: '1:925286111231:web:393e0565dec9db0b',
    messagingSenderId: '925286111231',
    projectId: 'mybooks-9bf04',
    authDomain: 'mybooks-9bf04.firebaseapp.com',
    databaseURL: 'https://mybooks-9bf04.firebaseio.com',
    storageBucket: 'mybooks-9bf04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzcoxB5_wC2x5BBzo2TFug3kI_I_TC0Uo',
    appId: '1:925286111231:android:46d39bca3045c625e1b9ca',
    messagingSenderId: '925286111231',
    projectId: 'mybooks-9bf04',
    databaseURL: 'https://mybooks-9bf04.firebaseio.com',
    storageBucket: 'mybooks-9bf04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfUhvo5ZSmwRNxuunRB7b5WKfQw9vIyBY',
    appId: '1:925286111231:ios:443dfaa8584e10f6e1b9ca',
    messagingSenderId: '925286111231',
    projectId: 'mybooks-9bf04',
    databaseURL: 'https://mybooks-9bf04.firebaseio.com',
    storageBucket: 'mybooks-9bf04.appspot.com',
    iosClientId: '925286111231-a4roqmnkrmormhb3a6gbmn1gksn96h2m.apps.googleusercontent.com',
    iosBundleId: 'com.elseif.ecolerrors',
  );
}
