// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'ecollogss.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class EcollLogssFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD83kcP3M_hqI9v_wj4YMhrskO25cm6UrQ',
    appId: '1:786151158207:web:9f891c1b1fc0c62343b10a',
    messagingSenderId: '786151158207',
    projectId: 'ecollogss',
    authDomain: 'ecollogss.firebaseapp.com',
    databaseURL: 'https://ecollogss-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecollogss.appspot.com',
    measurementId: 'G-Z8D2M9BLF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB59gDlLbMKHXTIp0JGobkGIV-G-sSjX9M',
    appId: '1:786151158207:android:7b32fa2a4e704fc343b10a',
    messagingSenderId: '786151158207',
    projectId: 'ecollogss',
    databaseURL: 'https://ecollogss-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecollogss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9TBgiANBAqJF4rYG8wfkY_dWeaoybhUE',
    appId: '1:786151158207:ios:c29231f0f95759c043b10a',
    messagingSenderId: '786151158207',
    projectId: 'ecollogss',
    databaseURL: 'https://ecollogss-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecollogss.appspot.com',
    iosClientId: '786151158207-s26ba0dpan9u5odk1i61uq3q15bcdv1v.apps.googleusercontent.com',
    iosBundleId: 'com.elseif.ecollogs',
  );
}
